version: 0.2
phases:
  install:
    commands:
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - echo Start build ...
      - pnpm build
artifacts:
  files:
    - '**/*'
  exclude-paths: 'src'
